module.exports = {
  USER_NOT_FOUND: 'User not found',
  CAR_NOT_FOUND: 'Car not found',
  EMPTY_FIELDS: 'Fields are empty',
  ALREADY_EXIST: 'Already exist',
  UPDATED: 'Updated',
  DELETED: 'Deleted',
  WRONG_DATA: 'Email or password is wrong',
  NOT_FOUND_MESSAGE: 'Not found',
  CREATED: 'Created',
  WELCOME: 'Welcome',
  FORBIDDEN: 'FORBIDDEN',
  AUTHORIZATION: 'Authorization',
  NOT_TOKEN: 'no token',
  INVALID_TOKEN: 'invalid token',
  OK: 'ok',
  WRONG_TEMPLATE_NAME: 'wrong template name',
  WRONG_TOKEN_TYPE: 'wrong token type',
  BIG_FILE: 'big file',
  CORS_NOT_ALLOWED: 'cors not allowed',
};
